baseurl = "https://pawa.lt/"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Peyton Walters"

enableRobotsTXT = true

pygmentsCodefences = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  # need to disable fractions to protect ip prefix notation (192.168.2.4/30)
  fractions = false

[taxonomies]
  category = "categories"
  ingredient = "ingredients"
  group = "groups"
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  
  avatar = "/img/avatar.jpg"

  fractions = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Peyton Walters"
  keywords = "homepage, blog, networking, linux, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"


  [[params.social]]
    name = "email"
    url = "mailto:pawalt@hey.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/pawalt"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/peywalt"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/pawalt/"

[languages]
  [languages.en]
    title = "Peyton Walters"
    subtitle = ""
    keywords = "im peyton"
    copyright = "Peyton Walters"

    [languages.en.params.logo]
      logoText = "/home/peyton/ $"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
  [[menu.main]]
    identifier = "recipes"
    name = "Food"
    url = "/recipes"
